[package]
name = "runner"
version = "0.2.0"
edition = "2024"

[[bin]]
name = "evo-runner"
path = "src/main.rs"

[dependencies]
evo-agent-sdk = { path = "../evo-agent-sdk" }
tokio         = { version = "1", features = ["full"] }
anyhow        = "1.0"
